spring.application.name=bai04

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bai04_ss19?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

#Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Config pagination
page_employee_size = 2

##Config jwt
jwt-secret=chuoidetaorakhoabimatsudungtrongjwt
#Chuỗi token tồn tại trong tgian 10phut
jwt-expired = 600000
#chuỗi refresh token tồn tại trong tgian 24 giờ
jwt-refresh-expired = 86400000